### ISSUE TITLE
Creds: use $HOME/.aws/credentials or allow importing from it

### ISSUE THREAD

**Issue by janost** [baliame/awsc#1]

**Comment by nick-doyle-slalom** [comment]
I second this. I suspect @baliame has a common use case of jumping between AWS accounts, but for me (and I suspect most others), typical use case is first CLI auth into one account (default profile), then do my business.

If that's the case, perhaps optimal would be, on launch import contexts from ~/.aws/credentials, and use default (or first one)?

**Comment by baliame** [comment]
Feature has been released in 0.3.1. I'll leave this open in case it's not working appropriately, and there's some improvements to be done (use "default" as default context on first launch, import .aws/config).
