### ISSUE TITLE
SSH: support ec2-instance-connect and/or SSH-over-SSM-tunnel

### ISSUE THREAD

**Issue by janost** [baliame/awsc#3]
So the user won't have to deal with SSH keys.
The program could validate the required SSM IAM policy on EC2 instances before attempting to set up a tunnel.

**Comment by baliame** [comment]
EC2 instance connect has been implemented.

SSH over SSM is a possibility down the road but requires the implementation of a lot of SSM-related features, and possibly IAM so we have a better insight into what's possible as the active user. I'll track that separately.
